### ISSUE TITLE
How to use this library

### ISSUE THREAD

**Issue by varunsngl** [epsilonlabsllc/DataManagement#7]
Hi, 

I liked this project and I want to use this as a library in my project. Please help me how can I do this. Till now I have used jcenter gradle dependency. But don't know how to do it manually. Please help.

Thanks in advance.

**Comment by tcaputi** [comment]
This project was written before Android was really using Gradle and hasn't been maintained since (I am no longer doing Android development). The easiest thing to do is probably just to bring the source code into your project. I can't really guarantee that will work but it's the best suggestion I have. Sorry.

**Comment by varunsngl** [comment]
Thanks for the reply. I'll find something else.
